version: "3.9"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: fleetlink
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: runner
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://wajhoor2001:Jaguar2001@cluster0.xcxg2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./:/app # useful for dev (hot reload); remove in production
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
